export const TASK_LISTS_FETCHED = 'TASK_LISTS_FETCHED';
export const TASK_LIST_CREATED = 'TASK_LIST_CREATED';
export const TASK_LIST_DELETED = 'TASK_LIST_DELETED';

export const TASKS_FETCHED = 'TASKS_FETCHED';
export const TASK_CREATED = 'TASK_CREATED';
export const TASK_UPDATED = 'TASK_UPDATED';
export const TASK_DELETED = 'TASK_DELETED';
